### ISSUE TITLE
KeyError: 'startup'

### ISSUE THREAD

**Issue by DavidWalz** [wilhelmer/mkdocs-unused-files#9]
I'm getting the following error on `mkdocs build` and `mkdocs serve`. Does someone have a clue what the issue could be?
@wilhelmer thanks for building this plugin!

```python
INFO     -  Building documentation...
Traceback (most recent call last):
  File "\Miniconda3\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "\Miniconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "\Miniconda3\Scripts\mkdocs.exe\__main__.py", line 7, in <module>
  File "\Miniconda3\lib\site-packages\click\core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "\Miniconda3\lib\site-packages\click\core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "\Miniconda3\lib\site-packages\click\core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "\Miniconda3\lib\site-packages\click\core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "\Miniconda3\lib\site-packages\click\core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "\Miniconda3\lib\site-packages\mkdocs\__main__.py", line 181, in serve_command
    serve.serve(dev_addr=dev_addr, livereload=livereload, watch=watch, **kwargs)
  File "\Miniconda3\lib\site-packages\mkdocs\commands\serve.py", line 63, in serve
    config = builder()
  File "\Miniconda3\lib\site-packages\mkdocs\commands\serve.py", line 37, in builder
    config = load_config(
  File "\Miniconda3\lib\site-packages\mkdocs\config\base.py", line 224, in load_config
    errors, warnings = cfg.validate()
  File "\Miniconda3\lib\site-packages\mkdocs\config\base.py", line 108, in validate
    run_failed, run_warnings = self._validate()
  File "\Miniconda3\lib\site-packages\mkdocs\config\base.py", line 63, in _validate
    self[key] = config_option.validate(value)
  File "\Miniconda3\lib\site-packages\mkdocs\config\config_options.py", line 132, in validate
    return self.run_validation(value)
  File "\Miniconda3\lib\site-packages\mkdocs\config\config_options.py", line 690, in run_validation
    plgins[item] = self.load_plugin(item, cfg)
  File "\Miniconda3\lib\site-packages\mkdocs\plugins.py", line 87, in __setitem__
    self._register_event(event_name[3:], method)
  File "\Miniconda3\lib\site-packages\mkdocs\plugins.py", line 74, in _register_event
    self.events[event_name].append(method)
KeyError: 'startup'
```

Versions used

* mkdocs 1.3.1
* mkdocs-material 8.4.2
* mkdocs-unused-files 0.2.0
* beautifulsoup4 4.12.3

**Comment by DavidWalz** [comment]
Ok, fixed by updating mkdocs & mkdocs-material.
